//! # D-Bus interface proxy for: `com.timekpr.server.admin`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `timkpr.server.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "com.timekpr.server.admin", assume_defaults = true)]
pub trait admin {
    /// getTimekprConfiguration method
    #[zbus(name = "getTimekprConfiguration")]
    fn get_timekpr_configuration(
        &self,
    ) -> zbus::Result<(
        i32,
        String,
        std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    )>;

    /// logCachedProcesses method
    #[zbus(name = "logCachedProcesses")]
    fn log_cached_processes(&self, pUserId: &str) -> zbus::Result<()>;

    /// setTimekprFinalNotificationTime method
    #[zbus(name = "setTimekprFinalNotificationTime")]
    fn set_timekpr_final_notification_time(
        &self,
        pFinalNotificationTimeSecs: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTimekprFinalWarningTime method
    #[zbus(name = "setTimekprFinalWarningTime")]
    fn set_timekpr_final_warning_time(
        &self,
        pFinalWarningTimeSecs: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTimekprLogLevel method
    #[zbus(name = "setTimekprLogLevel")]
    fn set_timekpr_log_level(&self, pLogLevel: i32) -> zbus::Result<(i32, String)>;

    /// setTimekprPlayTimeEnabled method
    #[zbus(name = "setTimekprPlayTimeEnabled")]
    fn set_timekpr_play_time_enabled(&self, pPlayTimeEnabled: bool) -> zbus::Result<(i32, String)>;

    /// setTimekprPlayTimeEnhancedActivityMonitorEnabled method
    #[zbus(name = "setTimekprPlayTimeEnhancedActivityMonitorEnabled")]
    fn set_timekpr_play_time_enhanced_activity_monitor_enabled(
        &self,
        pPlayTimeAdvancedSearchEnabled: bool,
    ) -> zbus::Result<(i32, String)>;

    /// setTimekprPollTime method
    #[zbus(name = "setTimekprPollTime")]
    fn set_timekpr_poll_time(&self, pPollTimeSecs: i32) -> zbus::Result<(i32, String)>;

    /// setTimekprSaveTime method
    #[zbus(name = "setTimekprSaveTime")]
    fn set_timekpr_save_time(&self, pSaveTimeSecs: i32) -> zbus::Result<(i32, String)>;

    /// setTimekprSessionsCtrl method
    #[zbus(name = "setTimekprSessionsCtrl")]
    fn set_timekpr_sessions_ctrl(&self, pSessionsCtrl: &[&str]) -> zbus::Result<(i32, String)>;

    /// setTimekprSessionsExcl method
    #[zbus(name = "setTimekprSessionsExcl")]
    fn set_timekpr_sessions_excl(&self, pSessionsExcl: &[&str]) -> zbus::Result<(i32, String)>;

    /// setTimekprTerminationTime method
    #[zbus(name = "setTimekprTerminationTime")]
    fn set_timekpr_termination_time(
        &self,
        pTerminationTimeSecs: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTimekprTrackInactive method
    #[zbus(name = "setTimekprTrackInactive")]
    fn set_timekpr_track_inactive(&self, pTrackInactive: bool) -> zbus::Result<(i32, String)>;

    /// setTimekprUsersExcl method
    #[zbus(name = "setTimekprUsersExcl")]
    fn set_timekpr_users_excl(&self, pUsersExcl: &[&str]) -> zbus::Result<(i32, String)>;
}
