//! # D-Bus interface proxy for: `com.timekpr.server.user.admin`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `timkpr.server.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "com.timekpr.server.user.admin", assume_defaults = true)]
pub trait admin {
    /// getUserInformation method
    #[zbus(name = "getUserInformation")]
    fn get_user_information(
        &self,
        p_user_name: &str,
        p_info_lvl: &str,
    ) -> zbus::Result<(
        i32,
        String,
        std::collections::HashMap<String, zbus::zvariant::OwnedValue>,
    )>;

    /// getUserList method
    #[zbus(name = "getUserList")]
    fn get_user_list(&self) -> zbus::Result<(i32, String, Vec<Vec<String>>)>;

    /// setAllowedDays method
    #[zbus(name = "setAllowedDays")]
    fn set_allowed_days(
        &self,
        p_user_name: &str,
        p_day_list: &[&str],
    ) -> zbus::Result<(i32, String)>;

    /// setAllowedHours method
    #[zbus(name = "setAllowedHours")]
    fn set_allowed_hours(
        &self,
        p_user_name: &str,
        p_day_number: &str,
        p_hour_list: std::collections::HashMap<&str, std::collections::HashMap<&str, i32>>,
    ) -> zbus::Result<(i32, String)>;

    /// setHideTrayIcon method
    #[zbus(name = "setHideTrayIcon")]
    fn set_hide_tray_icon(
        &self,
        p_user_name: &str,
        p_hide_tray_icon: bool,
    ) -> zbus::Result<(i32, String)>;

    /// setLockoutType method
    #[zbus(name = "setLockoutType")]
    fn set_lockout_type(
        &self,
        p_user_name: &str,
        p_lockout_type: &str,
        p_wake_from: &str,
        p_wake_to: &str,
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeActivities method
    #[zbus(name = "setPlayTimeActivities")]
    fn set_play_time_activities(
        &self,
        p_user_name: &str,
        p_play_time_activities: &[&[&str]],
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeAllowedDays method
    #[zbus(name = "setPlayTimeAllowedDays")]
    fn set_play_time_allowed_days(
        &self,
        p_user_name: &str,
        p_play_time_allowed_days: &[&str],
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeEnabled method
    #[zbus(name = "setPlayTimeEnabled")]
    fn set_play_time_enabled(
        &self,
        p_user_name: &str,
        p_play_time_enabled: bool,
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeLeft method
    #[zbus(name = "setPlayTimeLeft")]
    fn set_play_time_left(
        &self,
        p_user_name: &str,
        p_operation: &str,
        p_time_left: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeLimitOverride method
    #[zbus(name = "setPlayTimeLimitOverride")]
    fn set_play_time_limit_override(
        &self,
        p_user_name: &str,
        p_play_time_limit_override: bool,
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeLimitsForDays method
    #[zbus(name = "setPlayTimeLimitsForDays")]
    fn set_play_time_limits_for_days(
        &self,
        p_user_name: &str,
        p_play_time_limits: &[i32],
    ) -> zbus::Result<(i32, String)>;

    /// setPlayTimeUnaccountedIntervalsEnabled method
    #[zbus(name = "setPlayTimeUnaccountedIntervalsEnabled")]
    fn set_play_time_unaccounted_intervals_enabled(
        &self,
        p_user_name: &str,
        p_play_time_unaccounted_intervals_enabled: bool,
    ) -> zbus::Result<(i32, String)>;

    /// setTimeLeft method
    #[zbus(name = "setTimeLeft")]
    fn set_time_left(
        &self,
        p_user_name: &str,
        p_operation: &str,
        p_time_left: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTimeLimitForDays method
    #[zbus(name = "setTimeLimitForDays")]
    fn set_time_limit_for_days(
        &self,
        p_user_name: &str,
        p_day_limits: &[i32],
    ) -> zbus::Result<(i32, String)>;

    /// setTimeLimitForMonth method
    #[zbus(name = "setTimeLimitForMonth")]
    fn set_time_limit_for_month(
        &self,
        p_user_name: &str,
        p_time_limit_month: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTimeLimitForWeek method
    #[zbus(name = "setTimeLimitForWeek")]
    fn set_time_limit_for_week(
        &self,
        p_user_name: &str,
        p_time_limit_week: i32,
    ) -> zbus::Result<(i32, String)>;

    /// setTrackInactive method
    #[zbus(name = "setTrackInactive")]
    fn set_track_inactive(
        &self,
        p_user_name: &str,
        p_track_inactive: bool,
    ) -> zbus::Result<(i32, String)>;
}
