//! # D-Bus interface proxy for: `com.timekpr.server.user.limits`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `timkpr.server.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "com.timekpr.server.user.limits", assume_defaults = true)]
pub trait limits {
    /// requestTimeLeft method
    #[zbus(name = "requestTimeLeft")]
    fn request_time_left(&self, p_user_name: &str) -> zbus::Result<(i32, String)>;

    /// requestTimeLimits method
    #[zbus(name = "requestTimeLimits")]
    fn request_time_limits(&self, p_user_name: &str) -> zbus::Result<(i32, String)>;
}
